### ISSUE TITLE
uploaded songs

### ISSUE THREAD

**Issue by kasperm888-star** [mostafaalagamy/Metrolist#1549]
### Checklist

- [x] I've checked that there is no other issue about this feature request.
- [x] This issue contains only one feature request.
- [x] The title of this issue accurately describes the feature request.

### Feature description

honestly kinda new to this so idk if it's possible, but it'd be cool if the songs I've uploaded on the yt music website would work on metrolist

### Why do you want this feature?

.

### Additional information

.

**Comment by FullerBread2032** [comment]
Hi!
I understand that the uploaded songs are not displayed anywhere in the library.
Since I don't use this functionality much in YT Music, I'd like to ask if a special playlist would be enough (something similar to liked, cache, downloaded). 

If possible, try adding the downloaded song to any playlist and see if you can listen to it in Metrolist.

**Comment by kasperm888-star** [comment]
> Hi! I understand that the uploaded songs are not displayed anywhere in the library. Since I don't use this functionality much in YT Music, I'd like to ask if a special playlist would be enough (something similar to liked, cache, downloaded).
> 
> If possible, try adding the downloaded song to any playlist and see if you can listen to it in Metrolist.

if itd let me add the uploaded songs to my normal playlists it'd be great, i thought I'd add that the songs I have uploaded to yt music and added to my playlists do show up, however, when I play them, an error shows, as shown (I think)

![Image](https://github.com/user-attachments/assets/ebe38ea5-eb8d-454c-8cb0-89a3147adf29)

**Comment by Marko-98** [comment]
I experienced the same. I think it has something to do with uploaded music files being private and not accessible outside of the account that uploaded it. Basically, private YouTube videos (uploaded music gets their video ID normally).

Considering Metrolist allows you to sign in with YouTube Music account, it should be able to play these songs.

@FullerBread2032 Metrolist is probably trying to access the video ID without an account so that's why it can't play or download uploaded songs.

**Comment by FullerBread2032** [comment]
Yes, all uploaded songs are only available for account that uploaded this
This is a limitation of YouTube Music, and Metrolist can't change it. However, I can suggest adding a playlist that includes all the downloaded songs.

https://support.google.com/youtubemusic/answer/9716522?hl=en

**Comment by kasperm888-star** [comment]
> Yes, all uploaded songs are only available for account that uploaded this This is a limitation of YouTube Music, and Metrolist can't change it. However, I can suggest adding a playlist that includes all the downloaded songs.
> 
> https://support.google.com/youtubemusic/answer/9716522?hl=en

that's not the issue, I'm fine uploading the music to my account, but even when I'm logged in, metrolist can't play my uploaded songs. maybe this can't be fixed, but I hope it can because I do upload a lot of music

**Comment by Marko-98** [comment]
@FullerBread2032 Playlists aren't the issue. You can add uploaded song to any playlist you want and it still won't play because Metrolist doesn't have access to that video ID.

@kasperm888-star It can be fixed. Metrolist just need to request the uploaded songs from YouTube Music and with the request serve your account token, hash or cookie in order to prove YouTube Music you as an owner are accessing the song. From what I understand, it doesn't do that and instead pulls songs like you aren't signed with account.

**Comment by kasperm888-star** [comment]
> [@FullerBread2032](https://github.com/FullerBread2032) Playlists aren't the issue. You can add uploaded song to any playlist you want and it still won't play because Metrolist doesn't have access to that video ID.
> 
> [@kasperm888-star](https://github.com/kasperm888-star) It can be fixed. Metrolist just need to request the uploaded songs from YouTube Music and with the request serve your account token, hash or cookie in order to prove YouTube Music you as an owner are accessing the song. From what I understand, it doesn't do that and instead pulls songs like you aren't signed with account.

that's good news, i hope this can be fixed, thank you for the help!

**Comment by iyan1998** [comment]
> > Yes, all uploaded songs are only available for account that uploaded this This is a limitation of YouTube Music, and Metrolist can't change it. However, I can suggest adding a playlist that includes all the downloaded songs.
> > https://support.google.com/youtubemusic/answer/9716522?hl=en
> 
> that's not the issue, I'm fine uploading the music to my account, but even when I'm logged in, metrolist can't play my uploaded songs. maybe this can't be fixed, but I hope it can because I do upload a lot of music

I hope so too since there are songs that are not available on youtube music so I have to download it somewhere else and upload it to youtube music

**Comment by FullerBread2032** [comment]
After testing this, I've been able to reproduce this bug.
I think I know what's going on, as the link is missing the 'pot' parameter.
After reading up, it's a client integrity token created by BotGuard.

Interestingly, all uploaded songs under a minute play successfully. This was mentioned in one of the bug descriptions in NewPipeExtractor. I'll try to fix it, although it seems quite difficult at the moment.

**Comment by FullerBread2032** [comment]
@kasperm888-star @Marko-98 @iyan1998 
Hi, I think I've fixed this bug and the uploaded songs are now playing correctly. 
Please test this version thoroughly to see if there are any other unwanted issues.

https://github.com/mostafaalagamy/Metrolist/actions/runs/17759337511

**Comment by Greenylie** [comment]
> [@kasperm888-star](https://github.com/kasperm888-star) [@Marko-98](https://github.com/Marko-98) [@iyan1998](https://github.com/iyan1998) Hi, I think I've fixed this bug and the uploaded songs are now playing correctly. Please test this version thoroughly to see if there are any other unwanted issues.
> 
> https://github.com/mostafaalagamy/Metrolist/actions/runs/17759337511

The songs themselves play without any issues. However, the "Go to album" option loads indefinitely.
The "Go to artist" option works fine.

Just for context: I added my first batch of songs (properly tagged and grouped under the same album), and they display correctly in both the YouTube Music app and website.

**Comment by iyan1998** [comment]
> > [@kasperm888-star](https://github.com/kasperm888-star) [@Marko-98](https://github.com/Marko-98) [@iyan1998](https://github.com/iyan1998) Hi, I think I've fixed this bug and the uploaded songs are now playing correctly. Please test this version thoroughly to see if there are any other unwanted issues.
> > https://github.com/mostafaalagamy/Metrolist/actions/runs/17759337511
> 
> The songs themselves play without any issues. However, the "Go to album" option loads indefinitely. The "Go to artist" option works fine.
> 
> Just for context: I added my first batch of songs (properly tagged and grouped under the same album), and they display correctly in both the YouTube Music app and website.

I'm so dumb and it's my first time interacting with this so how do you run the version the dev sent sorry bro :)

**Comment by Greenylie** [comment]
> I'm so dumb and it's my first time interacting with this so how do you run the version the dev sent sorry bro :)

Scroll to the bottom of the [link in the message](https://github.com/mostafaalagamy/Metrolist/actions/runs/17759337511) and download either the version for your phone or the universal one.
They’re zipped, so you’ll need to extract them first using your phone's file manager :)

**Comment by iyan1998** [comment]
> > I'm so dumb and it's my first time interacting with this so how do you run the version the dev sent sorry bro :)
> 
> Scroll to the bottom of the [link in the message](https://github.com/mostafaalagamy/Metrolist/actions/runs/17759337511) and download either the version for your phone or the universal one. They’re zipped, so you’ll need to extract them first using your phone's file manager :)

**Comment by iyan1998** [comment]
> > > I'm so dumb and it's my first time interacting with this so how do you run the version the dev sent sorry bro :)
> > 
> > 
> > Scroll to the bottom of the [link in the message](https://github.com/mostafaalagamy/Metrolist/actions/runs/17759337511) and download either the version for your phone or the universal one. They’re zipped, so you’ll need to extract them first using your phone's file manager :)

No wonder I don't see the download link I just need to change browser's ui to desktop view, but thanks anyway!

**Comment by FullerBread2032** [comment]
> > [@kasperm888-star](https://github.com/kasperm888-star) [@Marko-98](https://github.com/Marko-98) [@iyan1998](https://github.com/iyan1998) Hi, I think I've fixed this bug and the uploaded songs are now playing correctly. Please test this version thoroughly to see if there are any other unwanted issues.
> > 
> > https://github.com/mostafaalagamy/Metrolist/actions/runs/17759337511
> 
> The songs themselves play without any issues. However, the "Go to album" option loads indefinitely.
> The "Go to artist" option works fine.
> 
> Just for context: I added my first batch of songs (properly tagged and grouped under the same album), and they display correctly in both the YouTube Music app and website.

Hi, thanks for the insight, the current version was only intended to check if the songs were playing correctly.
I will try to add proper handling of albums and artists of uploaded songs and add the ability to view all uploaded songs in the library.

**Comment by Greenylie** [comment]
> Hi, thanks for the insight, the current version was only intended to check if the songs were playing correctly. I will try to add proper handling of albums and artists of uploaded songs and add the ability to view all uploaded songs in the library.

Thanks for clarifying! I wasn’t sure since the artist option was working fine. Looking forward to the updates!

**Comment by iyan1998** [comment]
> > > [@kasperm888-star](https://github.com/kasperm888-star) [@Marko-98](https://github.com/Marko-98) [@iyan1998](https://github.com/iyan1998) Hi, I think I've fixed this bug and the uploaded songs are now playing correctly. Please test this version thoroughly to see if there are any other unwanted issues.
> > > https://github.com/mostafaalagamy/Metrolist/actions/runs/17759337511
> > 
> > 
> > The songs themselves play without any issues. However, the "Go to album" option loads indefinitely.
> > The "Go to artist" option works fine.
> > Just for context: I added my first batch of songs (properly tagged and grouped under the same album), and they display correctly in both the YouTube Music app and website.
> 
> Hi, thanks for the insight, the current version was only intended to check if the songs were playing correctly. I will try to add proper handling of albums and artists of uploaded songs and add the ability to view all uploaded songs in the library.

Thank you!

**Comment by Marko-98** [comment]
@FullerBread2032 I can confirm uploaded songs play normally. Other issues were already mentioned so there's no need to mention them again.

Thanks for your work! I really appreciate it!

**Comment by kasperm888-star** [comment]
> [@kasperm888-star](https://github.com/kasperm888-star) [@Marko-98](https://github.com/Marko-98) [@iyan1998](https://github.com/iyan1998) Hi, I think I've fixed this bug and the uploaded songs are now playing correctly. Please test this version thoroughly to see if there are any other unwanted issues.
> 
> https://github.com/mostafaalagamy/Metrolist/actions/runs/17759337511

im so happy this works, thank you so much!

**Comment by FullerBread2032** [comment]
@kasperm888-star @Marko-98 @iyan1998 @Greenylie 
Hello!

I've added the ability to sync uploaded songs and albums to the Library section.
There's an "Uploaded" playlist there, which contains only uploaded songs. 
Clicking on "Songs" or "Albums" in the chips row will also display the "Uploaded" section.

I've also fixed the album preview, so it should now load normally.

> [!CAUTION]
> If you want to test the version, you should **back up the application data**, as the database has been updated. 
> The information in the database may still change, which could cause the application to crash later when launching new versions or reverting to the old ones. 

If you have any feature requests related to uploaded songs, let me know
Thanks!

Please test this version:
https://github.com/mostafaalagamy/Metrolist/actions/runs/17862265010

**Comment by iyan1998** [comment]
> [@kasperm888-star](https://github.com/kasperm888-star) [@Marko-98](https://github.com/Marko-98) [@iyan1998](https://github.com/iyan1998) [@Greenylie](https://github.com/Greenylie) Hello!
> 
> I've added the ability to sync uploaded songs and albums to the Library section. There's an "Uploaded" playlist there, which contains only uploaded songs. Clicking on "Songs" or "Albums" in the chips row will also display the "Uploaded" section.
> 
> I've also fixed the album preview, so it should now load normally.
> 
> Caution
> 
> If you want to test the version, you should **back up the application data**, as the database has been updated. The information in the database may still change, which could cause the application to crash later when launching new versions or reverting to the old ones.
> 
> If you have any feature requests related to uploaded songs, let me know Thanks!
> 
> Please test this version: https://github.com/mostafaalagamy/Metrolist/actions/runs/17862265010

You're a godsend!

**Comment by gursuj** [comment]
The uploads playlist shows up but the songs don't play. They show the same error message as shown in this [comment above](https://github.com/mostafaalagamy/Metrolist/issues/1549#issuecomment-3288426437). Happens on both the latest release and debug versions. ` adb logcat | findstr "com.metrolist.music.debug"` didn't show any new logs when I tried playing uploaded songs.

**Comment by Marko-98** [comment]
It works perfectly for me.

**Comment by gursuj** [comment]
Still doesn't work for me on the latest version. @FullerBread2032 any idea why this may be happening? 
Edit: As of v12.8.0, this works for me.

**Comment by iyan1998** [comment]
> Still doesn't work for me on the latest version. [@FullerBread2032](https://github.com/FullerBread2032) any idea why this may be happening?

Guys it's stop working for me :(

**Comment by grill-glitch** [comment]
the feature seems unavailable since 12.12.4,even if I installed the nightly build,error still occurs.

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/e71384e8-312d-4f52-b18c-b975229a3e28" />
