### ISSUE TITLE
add song on random queue already made is wrong

### ISSUE THREAD

**Issue by enomao44** [mostafaalagamy/Metrolist#1570]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [x] I've checked that there is no open or closed issue about this bug.
- [x] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

so when i create a random queue and after a while i want to listen and add a song just next to the song im listening, when im searching the song and i add it from the search section the song is being added as a random song also and is not played the next but when i do that for ex from inside an album the song goes next correctly

### Expected behavior

if you put play next and you have a random queue i want the song to play next not that goes randomly somewhere

### Actual behavior

the song is not going next

### Logs

idk

### Metrolist version

last

### Android version

android 12

**Comment by Tuyuyi99** [comment]
Same thing happening here

**Comment by Dr-Brixx** [comment]
@Tuyuyi99 @enomao44 I can't reproduce it, is it still happening to you in the newest nightly?

**Comment by Tuyuyi99** [comment]
> [@Tuyuyi99](https://github.com/Tuyuyi99) [@enomao44](https://github.com/enomao44) I can't reproduce it, is it still happening to you in the newest nightly?

This is quite old, it got fixed in a update a long time ago

Btw, what do you mean by newest nightly?

**Comment by Dr-Brixx** [comment]
That is great to hear. With nightly i just mean the newest that you can find [here](https://github.com/MetrolistGroup/Metrolist/actions/workflows/build.yml)

**Comment by Dr-Brixx** [comment]
@enomao44 if it's also fixed for you, could you be so kind and close this issue?

**Comment by enomao44** [comment]
no is not fixed for me in the last version for example neither, when a song is at shuffle mode for 10 songs for example of an album at shuffle, then im listening the song number 5 of the queue, and then i add a new song on the queue the song im listening and the song i added they go on the top place of the queue so that means im gonna listen again all the 4 previous songs i already listened. it has never been fixed this. did you try really the way im saying?

**Comment by Dr-Brixx** [comment]
Yeah, i tried it and I don't have that issue. Maybe a screen recording or log would help?

**Comment by Tuyuyi99** [comment]
> no is not fixed for me in the last version for example neither, when a song is at shuffle mode for 10 songs for example of an album at shuffle, then im listening the song number 5 of the queue, and then i add a new song on the queue the song im listening and the song i added they go on the top place of the queue so that means im gonna listen again all the 4 previous songs i already listened. it has never been fixed this. did you try really the way im saying?

Oh I get what you're saying now, it's happening to me too. You mean this? https://github.com/MetrolistGroup/Metrolist/issues/2617

**Comment by Dr-Brixx** [comment]
Huh, weird. I don't have that issue. The only problem I have is that shuffling shuffles all songs, even already listened ones, but that is probably intentional. Did you update to the [newest nightly](https://github.com/MetrolistGroup/Metrolist/actions/workflows/build.yml)? And after updating, force close in settings and clear cache, then relaunch the app.

**Comment by Tuyuyi99** [comment]
> Huh, weird. I don't have that issue. The only problem I have is that shuffling shuffles all songs, even already listened ones, but that is probably intentional. Did you update to the [newest nightly](https://github.com/MetrolistGroup/Metrolist/actions/workflows/build.yml)? And after updating, force close in settings and clear cache, then relaunch the app.

I've tested it rn in the nightly and it works like a charm, ty!

**Comment by enomao44** [comment]
> > no is not fixed for me in the last version for example neither, when a song is at shuffle mode for 10 songs for example of an album at shuffle, then im listening the song number 5 of the queue, and then i add a new song on the queue the song im listening and the song i added they go on the top place of the queue so that means im gonna listen again all the 4 previous songs i already listened. it has never been fixed this. did you try really the way im saying?
> 
> Oh I get what you're saying now, it's happening to me too. You mean this? [#2617](https://github.com/MetrolistGroup/Metrolist/issues/2617)

yeah exactly this is what i mean

**Comment by Dr-Brixx** [comment]
> > > no is not fixed for me in the last version for example neither, when a song is at shuffle mode for 10 songs for example of an album at shuffle, then im listening the song number 5 of the queue, and then i add a new song on the queue the song im listening and the song i added they go on the top place of the queue so that means im gonna listen again all the 4 previous songs i already listened. it has never been fixed this. did you try really the way im saying?
> > 
> > 
> > Oh I get what you're saying now, it's happening to me too. You mean this? [#2617](https://github.com/MetrolistGroup/Metrolist/issues/2617)
> 
> yeah exactly this is what i mean

Does it still happen to you in the [newest nightly](https://github.com/MetrolistGroup/Metrolist/actions/workflows/build.yml)?

**Comment by enomao44** [comment]
what is the nightly?

**Comment by Dr-Brixx** [comment]
Click [this](https://github.com/MetrolistGroup/Metrolist/actions/runs/24685631331) and either download app-release or app-with-Google-Cast and unzip it and then install the apk

**Comment by enomao44** [comment]
so you mean the basic app has not fixed this problem? app with google cast has more improvements?? basic app could be solved too maybe..

**Comment by nyxiereal** [comment]
Unable to reproduce in the current version - this appears to be fixed. Please reopen if you can still reproduce this on the latest release.

**Comment by enomao44** [comment]
> Click [this](https://github.com/MetrolistGroup/Metrolist/actions/runs/24685631331) and either download app-release or app-with-Google-Cast and unzip it and then install the apk

I just uninstalled and install the one with google cast and is the same. Is not working. The added songs go on top. Instead of staying at the same place.

**Comment by enomao44** [comment]
> > no is not fixed for me in the last version for example neither, when a song is at shuffle mode for 10 songs for example of an album at shuffle, then im listening the song number 5 of the queue, and then i add a new song on the queue the song im listening and the song i added they go on the top place of the queue so that means im gonna listen again all the 4 previous songs i already listened. it has never been fixed this. did you try really the way im saying?
> 
> Oh I get what you're saying now, it's happening to me too. You mean this? [#2617](https://github.com/MetrolistGroup/Metrolist/issues/2617)

This is not working for you neither then... we are mixing stuff here. The subject i was talking in this post is this video here that they go on top the songs added in shuffled queue. For example in riplay this in my phone is working okey.

**Comment by Dr-Brixx** [comment]
> so you mean the basic app has not fixed this problem? app with google cast has more improvements?? basic app could be solved too maybe..

Nightly is an in-development build of the app with the latest fixes and improvements.

And if that issue still occurs, could you please send logs and maybe screenrecording?

**Comment by enomao44** [comment]
Is happening the same of the video you shared. The added song and song playing they move on top of the queue...

**Comment by enomao44** [comment]
Nooooow is working . In thelast version 13.4.2 even in the basic apk... thank you so much so useful this fix
