### ISSUE TITLE
Discord RPC is not working properly again

### ISSUE THREAD

**Issue by Zareeff** [mostafaalagamy/Metrolist#1778]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [x] I've checked that there is no open or closed issue about this bug.
- [x] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play song
Go to discord
See the song playing
When you skip it or automatically play next it breaks (frozen)

### Expected behavior

Should show which song is playing and not be frozen.

### Actual behavior

Is frozen when a song is skipped

### Screenshots/Screen recordings

.

### Logs

.

### Metrolist version

12.7.0

### Android version

9

### Additional information

It was once fixed before. I think 12.7.0 update broke it, not sure.

**Comment by Zareeff** [comment]
Also this used to be the one where this issue was fixed https://github.com/mostafaalagamy/Metrolist/pull/1599

**Comment by Monoxide8969** [comment]
The latest update lists 
> Discord RPC Improvements - Enhanced Discord Rich Presence integration

Please check if the problem is still present for you, if not close this issue

**Comment by Zareeff** [comment]
> The latest update lists 
> > Discord RPC Improvements - Enhanced Discord Rich Presence integration
> 
> Please check if the problem is still present for you, if not close this issue
> 

The problem is still present. I would've already closed this if not.

**Comment by yatchaba** [comment]
This bug still occurs. When playing songs continuously, the second song onwards is not reflected in the Discord display. If you stop and restart playback, it will be reflected.
