### ISSUE TITLE
failed to get working stream

### ISSUE THREAD

**Issue by fagiln** [mostafaalagamy/Metrolist#640]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [x] I've checked that there is no open or closed issue about this bug.
- [x] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

can't listen to a single song yet

### Expected behavior

-

### Actual behavior

-

### Screenshots/Screen recordings

![Image](https://github.com/user-attachments/assets/fcf81687-20dd-4ddd-a2d1-b921163b7266)

### Logs

-

### Metrolist version

11.9.0

### Android version

12

**Comment by zettaexa** [comment]
I had this error before, just switch back and forth with another song and the error would go away, Very strange since this hasn't happened before the update but oh well

**Comment by CaptechOmar** [comment]
I'm having this erro too after the last update

**Comment by MetalDroid** [comment]
It seems the only working client is the iOS one, but the downside is that it often crashes with an "Unknown error" after 30 seconds.

I tried this change to the validateStatus method because it almost always returns false, so that it would at least work with iOS (but with the 30-second issue):

```
private fun validateStatus(url: String, client: YouTubeClient): Boolean {
        return try {
            val request = Request.Builder()
                .get()
                .url(url)
                .header("Range", "bytes=0-1")
                .header("User-Agent", client.userAgent)
                .build()
            val response = httpClient.newCall(request).execute()
            response.use { it.isSuccessful }
        } catch (e: Exception) {
            e.printStackTrace()
            false
        }
    }
```

and used like this:

`if (streamUrl == null || !validateStatus(streamUrl, client)) continue`

I'm afraid that until there is a solution to use the other clients, the problem is unsolved.

**Comment by Slawa79** [comment]
![Screenshot_2025-05-04-18-08-56-24_83e681264c35b676874c1b7737da0359.jpg](https://github.com/user-attachments/assets/b50993d0-d215-4d5f-955d-6fb7e0dad430)

This bug is in all third-party YouTube music clients. It doesn't even work with a VPN in Russia.

**Comment by MetalDroid** [comment]
I have no idea how Harmony Music works, but without using login it plays correctly. 

These errors are a nightmare

**Comment by mostafaalagamy** [comment]
> I have no idea how Harmony Music works, but without using login it plays correctly. 
> 
> These errors are a nightmare 

There is another method we can use to avoid all errors, but I am currently unable to do it because I am not using Android Studio at the moment.

**Comment by CaptechOmar** [comment]
No body touches anything.
It seems to be working fine for now

**Comment by mostafaalagamy** [comment]
> No body touches anything.
> It seems to be working fine for now

حاضر يا أشرف

**Comment by CaptechOmar** [comment]
Okay, it's broken again

**Comment by mostafaalagamy** [comment]
The issue happens to me randomly!

**Comment by mostafaalagamy** [comment]
resolved in latest debug version

**Comment by mostafaalagamy** [comment]
> I have no idea how Harmony Music works, but without using login it plays correctly. 
> 
> These errors are a nightmare 

I’ve integrated an external library to stream songs as a fallback when the current providers fail, resolving most of the errors we encountered.

**Comment by m-obeid** [comment]
Just tried the JossRedConnect implementation and it made "This video may be inappropriate for some users" turn into unknown error, huh.

**Comment by mostafaalagamy** [comment]
> Just tried the JossRedConnect implementation and it made "This video may be inappropriate for some users" turn into unknown error, huh.

Turn off the option and on it again from settings!

**Comment by mostafaalagamy** [comment]
![Screenshot_2025-05-05-00-01-54-679_com.metrolist.music.jpg](https://github.com/user-attachments/assets/6bca7416-930e-48cc-bee1-e7add6ed2c39)

Work for me!

**Comment by mostafaalagamy** [comment]
![Screenshot_2025-05-05-00-01-54-679_com.metrolist.music.jpg](https://github.com/user-attachments/assets/6bca7416-930e-48cc-bee1-e7add6ed2c39)

**Comment by m-obeid** [comment]
The service gets stuck on every single song, including already working songs, except that, even in Joss Music, so it‘s not Metrolist‘s fault. Maybe you should make Joss Red a fallback to fix some songs instead of fully relying on it.

**Comment by mostafaalagamy** [comment]
> The service gets stuck on every single song, including already working songs, except that, even in Joss Music, so it‘s not Metrolist‘s fault. Maybe you should make Joss Red a fallback to fix some songs instead of fully relying on it.

I didn’t rely on it completely—I only made it an optional way to play certain songs. I pushed a small change that fixed the stopping issue for me. Normally I never encounter the problems we’ve been discussing, but after the last update I started having trouble playing tracks, so the latest debug build has resolved the issue for me so far.

**Comment by mostafaalagamy** [comment]
> > The service gets stuck on every single song, including already working songs, except that, even in Joss Music, so it‘s not Metrolist‘s fault. Maybe you should make Joss Red a fallback to fix some songs instead of fully relying on it.
> 
> I didn’t rely on it completely—I only made it an optional way to play certain songs. I pushed a small change that fixed the stopping issue for me. Normally I never encounter the problems we’ve been discussing, but after the last update I started having trouble playing tracks, so the latest debug build has resolved the issue for me so far.
> 
> 

After writing that reply, the issue came up again. I’m really fed up with this; I just want to go to sleep.

**Comment by MetalDroid** [comment]
> > > The service gets stuck on every single song, including already working songs, except that, even in Joss Music, so it‘s not Metrolist‘s fault. Maybe you should make Joss Red a fallback to fix some songs instead of fully relying on it.
> > 
> > 
> > I didn’t rely on it completely—I only made it an optional way to play certain songs. I pushed a small change that fixed the stopping issue for me. Normally I never encounter the problems we’ve been discussing, but after the last update I started having trouble playing tracks, so the latest debug build has resolved the issue for me so far.
> 
> After writing that reply, the issue came up again. I’m really fed up with this; I just want to go to sleep.

It's real torture.

I even think I fixed NewPipe's getStreamUrl method so it doesn't return a null URL, but still, after a thousand tests, it still returns a 403 error, lol 

It's better to rest. There's probably another updated library that fixes these issues.

**Comment by zettaexa** [comment]
> I had this error before, just switch back and forth with another song and the error would go away, Very strange since this hasn't happened before the update but oh well

**Comment by Chulco** [comment]
Same here

**Comment by m-obeid** [comment]
Joss Red works for me now too! Probably was some internal issue with their API. But this doesn't solve uploaded music yet, we still need to wait for newpipeextractor for that ...

**Comment by m-obeid** [comment]
Download still needs to be fixed, if that's even possible?

**Comment by IgorTrud** [comment]
Joss Red looks to have the same issue.
Only 2-3 tracks from 10 start payling...
Yes, its not more "Failed to get working stream", but fails on timeout.

> 2025-05-06 09:11:53.920 10688-12242 MusicService            com.metrolist.music.debug            I  Usando Joss Red para reproducción
2025-05-06 09:11:53.921 10688-12242 MusicService            com.metrolist.music.debug            I  URL alternativa: https://jossred.josprox.com/yt/v2/stream/SqAxWiqBB2g
2025-05-06 09:12:03.933 10688-10739 ExoPlayerImplInternal   com.metrolist.music.debug            E  Playback error
                                                                                                      androidx.media3.exoplayer.ExoPlaybackException: Source error
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:864)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:836)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loop(Looper.java:223)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: java.io.IOException: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: timeout
                                                                                                          at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:278)
                                                                                                          at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
                                                                                                          at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
                                                                                                          at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:110)
                                                                                                          at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:88)
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1109)
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:453)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                          at java.lang.Thread.run(Thread.java:923)
                                                                                                      Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: timeout
                                                                                                          at androidx.media3.datasource.okhttp.OkHttpDataSource.executeCall(OkHttpDataSource.java:448)
                                                                                                          at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:273)
                                                                                                          at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275) 
                                                                                                          at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54) 
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802) 
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615) 
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802) 
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615) 
                                                                                                          at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:110) 
                                                                                                          at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:88) 
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1109) 
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:453) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                          at java.lang.Thread.run(Thread.java:923) 
                                                                                                      Caused by: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: timeout
                                                                                                          at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:292)
                                                                                                          at com.google.common.util.concurrent.AbstractFutureState.blockingGet(AbstractFutureState.java:252)
                                                                                                          at com.google.common.util.concurrent.Platform.get(Platform.java:54)
                                                                                                          at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:253)
                                                                                                          at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:96)
                                                                                                          at androidx.media3.datasource.okhttp.OkHttpDataSource.executeCall(OkHttpDataSource.java:443)
                                                                                                          at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:273) 
                                                                                                          at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275) 
                                                                                                          at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54) 
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802) 
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615) 
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802) 
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615) 
                                                                                                          at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:110) 
                                                                                                          at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:88) 
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1109) 
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:453) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                          at java.lang.Thread.run(Thread.java:923) 
                                                                                                      Caused by: java.net.SocketTimeoutException: timeout
                                                                                                          at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
                                                                                                          at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
                                                                                                          at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
                                                                                                          at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:97)
                                                                                                          at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
                                                                                                          at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
                                                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                          at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                                                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                          at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                                                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                          at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2025-05-06 09:12:03.933 10688-10739 ExoPlayerImplInternal   com.metrolist.music.debug            E        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                          at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                                                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                          at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                                                                                                          at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
                                                                                                          ... 3 more

**Comment by Spaceshiprace** [comment]
guys, this issue is only happening for songs that has age restriction, try these songs and see : 
- Holy Fucking Shit: 40,000
- HERMANOS by jpegmafia
and also videos with age restriction can't be played

**Comment by mostafaalagamy** [comment]
Try the latest debug version, all errors resolved for me after a full day of testing.

**Comment by frenchy82** [comment]
I tried the very Last de bug version and it sems to work well now. Didn't try enought to be sure, i Will try better tomorrow, but it works much better no.
congratulation devs !

**Comment by m-obeid** [comment]
The songs mentioned above seem to work now, but for some unknown reasons, I sometimes end up getting timeout

Tested not working: I Love to Say Fuck by Murderdolls

I don't think the issue is related to Metrolist but actually Joss Red:

If you do a GET request on https://jossred.josprox.com/yt/v2/stream/sBRYDjxsx08 currently it'll just keep loading and the stream in the end is broken (in fact it literally contains just a single null byte)

With one of the songs that work, like Fuck love by xxxtentaction:

https://jossred.josprox.com/yt/v2/stream/8aaoYbPXOPs

U can see it plays the stream inside the browser (assuming you're using chrome or firefox)

**Comment by m-obeid** [comment]
Songs take some time to work for some reason, so just wait and maybe it'll start working later.

And downloads from Joss Red don't work but I think that's just server side limitations because even downloading from within your browser fails.

But this works well as a workaround for now 👌🏼

**Comment by m-obeid** [comment]
![Image](https://github.com/user-attachments/assets/73140934-5b42-4119-8333-703e8c3485d1)

This is what happens when I try to download from browser, it just says "no file"

**Comment by zettaexa** [comment]
Sorry to ask but where does Joss Red come from? When I look it up it gives me Metrolist

**Comment by m-obeid** [comment]
It's from Joss Music, another InnerTune fork

https://github.com/josprox/Joss-Music

**Comment by zettaexa** [comment]
> It's from Joss Music, another InnerTune fork
> 
> https://github.com/josprox/Joss-Music

So they have their own stream/api?

**Comment by m-obeid** [comment]
> > It's from Joss Music, another InnerTune fork
> > https://github.com/josprox/Joss-Music
> 
> So they have their own stream/api?

Correct

**Comment by MetalDroid** [comment]
For now everything works correctly in the debug build (even without using Joss).

Very good work 👍

**Comment by Spaceshiprace** [comment]
> The songs mentioned above seem to work now, but for some unknown reasons, I sometimes end up getting timeout
> 
> Tested not working: I Love to Say Fuck by Murderdolls
> 
> I don't think the issue is related to Metrolist but actually Joss Red:
> 
> If you do a GET request on https://jossred.josprox.com/yt/v2/stream/sBRYDjxsx08 currently it'll just keep loading and the stream in the end is broken (in fact it literally contains just a single null byte)
> 
> With one of the songs that work, like Fuck love by xxxtentaction:
> 
> https://jossred.josprox.com/yt/v2/stream/8aaoYbPXOPs
> 
> U can see it plays the stream inside the browser (assuming you're using chrome or firefox)

what?, regarding the songs now its showing unknown issue for me

**Comment by mostafaalagamy** [comment]
> what?, regarding the songs now its showing unknown issue for me

Age verification? Turn on joss option in player settings!

**Comment by mostafaalagamy** [comment]
> > what?, regarding the songs now its showing unknown issue for me
> 
> Age verification? Turn on joss option in player settings!

![Screenshot_2025-05-07-04-10-47-287_com.metrolist.music.jpg](https://github.com/user-attachments/assets/9e3ad6ec-a195-4123-b83b-3750d1c28534)

![Screenshot_2025-05-07-04-10-18-855_com.metrolist.music.jpg](https://github.com/user-attachments/assets/edf23170-ba60-4853-aab6-47516171652d)

**Comment by Spaceshiprace** [comment]
@mostafaalagamy 
sorry, yea it worked but after i turned the option off and re-turn it again

**Comment by Spaceshiprace** [comment]
@mostafaalagamy 
also noticed that when i click details for these songs it doesn't give much information about it as other normal songs, try and see..

**Comment by mostafaalagamy** [comment]
> @mostafaalagamy 
> also noticed that when i click details for these songs it doesn't give much information about it as other normal songs, try and see..

song will only play online, no other option works.

**Comment by Spaceshiprace** [comment]
does that mean it can't be downloaded ??

**Comment by mostafaalagamy** [comment]
> does that mean it can't be downloaded ??

no download no cache! online only.

**Comment by Spaceshiprace** [comment]
damn. i hope if there will be any other solution cuz that seems like a really bad issue

**Comment by MetalDroid** [comment]
> [@mostafaalagamy](https://github.com/mostafaalagamy) sorry, yea it worked but after i turned the option off and re-turn it again

That seems strange to me, if following those steps works, maybe that logic can be automated 🧐

**Comment by qwertyxdd1** [comment]
How can I get latest debug version? Can someone send me APK?

**Comment by m-obeid** [comment]
In actions tab > build apks > last successful build > at the very bottom
there’s apks

**Comment by zettaexa** [comment]
> > does that mean it can't be downloaded ??
> 
> no download no cache! online only.

Dang, hope there's a fix for this since i rlly like cached/downloaded music features

**Comment by mostafaalagamy** [comment]
> Dang, hope there's a fix for this since i rlly like cached/downloaded music features

This only happens for songs that need age verification.

**Comment by zettaexa** [comment]
> > Dang, hope there's a fix for this since i rlly like cached/downloaded music features
> 
> This only happens for songs that need age verification.

Ok good bc i rarely listen to those songs

**Comment by zettaexa** [comment]
Never got the issue in the first place but i did notice tracks getting a bit slower to load after 11.9 Nothing too bad i can wait it out, Good that you published the version w/ joss red though, Very useful even outside this situation 👍

**Comment by Spaceshiprace** [comment]
> > > Dang, hope there's a fix for this since i rlly like cached/downloaded music features
> > 
> > 
> > This only happens for songs that need age verification.
> 
> Ok good bc i rarely listen to those songs

to me its a really bad thing, since i listen to alot bangers that is age restricted 🙁
